export const FETCH_QUERY_ERROR = 'FETCH_QUERY_ERROR';
export const FETCH_QUERY_SUCCESS = 'FETCH_QUERY_SUCCESS';
export const FETCH_QUERY_REQUEST = 'FETCH_QUERY_REQUEST';
export const FETCH_SUGGESTIONS_SUCCESS = 'FETCH_SUGGESTIONS_SUCCESS';
export const FETCH_SUGGESTIONS_ERROR = 'FETCH_SUGGESTIONS_ERROR';
export const FETCH_SUGGESTIONS_REQUEST = 'FETCH_SUGGESTIONS_REQUEST';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';